version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: NPM test
          command: npm test

  deploy:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Compile to production
          command: npm run build
      - run:
          name: Deploy code to server
          command: scp -r ./build/* $DEPLOYMENT_USER@$DEPLOYMENT_HOST:$DEPLOYMENT_DIR

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
              branches:
                only: master
